### ISSUE TITLE
Error: Failed to parse declaration "transform"

### ISSUE THREAD

**Issue by long-nc** [vadimdemedes/tailwind-rn#123]
I was trying tailwind-rn 4.0.0 and had a build issue
<b>
Error: Failed to parse declaration "transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))"
</b>

Comparing to previous version, v4.0.0 doesn't omit unsupported styles which causes error in `css-to-react-native` lib.
Did you experience this issue before?

**Comment by vadimdemedes** [comment]
This is expected behavior, because like you said, latest release doesn't omit unsupported styles and doesn't maintain an allowlist/denylist of utilities anymore. Because Tailwind's JIT compiler can essentially produce any possible CSS, it'd be a pain in the ass to somehow detect the unsupported rules and skip them.

Instead, it's expected that you don't use utilities that aren't listed in ["Supported Utilities"](https://github.com/vadimdemedes/tailwind-rn#supported-utilities) section in the readme.

**Comment by long-nc** [comment]
That's weird because, in my case, I didn't intend to use `transform` style but somehow tailwind JIT still generated it

**Comment by long-nc** [comment]
I found out that JIT accidentally mapped RN styles into it's own css class
e.g.
```
<Animated.View
  style={[
    styles.dot,
    {
      backgroundColor: radioColor,
      transform: [{ scale: radioAnim }],
    },
  ]}
/>
```

**Comment by HeleneGrini** [comment]
Disabling the properties that are not supported work for me. Add this to your tailwind config 

```
  corePlugins: {
    boxShadow: false,
    translate: false, 
    transform: false, 
    ringWidth: false
  }
```

I dont use these classes, but the css was still being generated. This should perhaps be added to the readme?

**Comment by long-nc** [comment]
> Disabling the properties that are not supported worked for me. Add this to your tailwind config
> 
> ```
>   corePlugins: {
>     boxShadow: false,
>     translate: false, 
>     transform: false, 
>     ringWidth: false
>   }
> ```
> 
> I dont use these classes, but the css was still being generated. This should perhaps be added to the readme?

Thanks, that's really helpful

**Comment by vadimdemedes** [comment]
Are you using Tailwind 3.x? I suspect that you're not, because if you're not using a transform utility, Tailwind shouldn't even generate that class with `transform` in it.

**Comment by long-nc** [comment]
Check out [my demo](https://github.com/long-nc/tailwind-rn-4-demo) if you have time. I created a new project using `tailwindcss: 3.0.12` and `tailwind-rn: 4.0.0` and still got the same issue.

After tailwindcss scanned through my [Box](https://github.com/long-nc/tailwind-rn-4-demo/blob/master/src/Box.js) component
```jsx
import React from 'react';
import { useTailwind } from 'tailwind-rn';
import { StyleSheet, View } from 'react-native';

const Box = () => {
  const tw = useTailwind();
  return <View style={[styles.box, tw('bg-black h-[100px] w-[100-px]')]} />;
}

const styles = StyleSheet.create({
  box: {
    transform: { scale: 2 },
  }
});

export default Box;
```
And here's what it generated
```css
.h-\[100px\] {
  height: 100px
}

.w-\[100-px\] {
  width: 100 - px
}

.transform {
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
}

.bg-black {
  --tw-bg-opacity: 1;
  background-color: rgb(0 0 0 / var(--tw-bg-opacity))
}
```
