### ISSUE TITLE
How to make a shadow utility?

### ISSUE THREAD

**Issue by buitrbao222** [vadimdemedes/tailwind-rn#139]
I added a utility in `tailwind.config.js` as follow:
```javascript
plugins: [
  plugin(function ({ addUtilities, matchUtilities }) {
    addUtilities({
      '.box-card-shadow': {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: '0.23',
        shadowRadius: '2.62px',
        elevation: '4',
      },
    });
  }),
],
```

Expected Results:
```javascript
/* tailwind.json */
"box-card-shadow": {
  "style": {
    "shadowColor": "#000",
    "shadowOffset": {
      "width": 0,
      "height": 2,
    },
    "shadowOpacity": 0.23,
    "shadowRadius": 2.62,
    "elevation": 4,
  }
}
```

Actual Results
```javascript
/* tailwind.json */
"box-card-shadow": {
  "style": {
    "shadowOpacity": 0.23,
    "shadowRadius": 2.62,
    "elevation": 4
  }
},
"box-card-shadow shadowOffset": {
  "style": {
    "width": 0,
    "height": 2
  }
},
```

```css
/* tailwind.css */
.box-card-shadow {
  shadow-color: #000;
}

.box-card-shadow shadowOffset {
  width: 0;
  height: 2px;
}

.box-card-shadow {
  shadow-opacity: 0.23;
  shadow-radius: 2.62px;
  elevation: 4;
}
```
