### ISSUE TITLE
Is TailwindCSS component available with this library?

### ISSUE THREAD

**Issue by Papillon6814** [vadimdemedes/tailwind-rn#184]
Hello. I'm trying to use [daisyUI](https://daisyui.com/) with this library.
So I installed it by `npm i daisyui` and wrote some configurations in `tailwind.config.js`.
```js
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: ["light"]
  },
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
```

And made `Main` component for tryout.
```tsx
import { Text, View } from 'react-native';
import { useTailwind } from 'tailwind-rn';

const Main = () => {
  const tailwind = useTailwind()

  return (
    <View style={tailwind('bg-blue-100 h-full w-full')}>
      <Text style={tailwind('text-primary')}>Open up App.tsx to start working on your app!</Text>
    </View>
  )
}

export default Main
```

I ran `npm run build:tailwind` and it generated CSS in `tailwind.css` for the app, it is like this:
```css
:root,
[data-theme] {
  background-color: hsla(var(--b1) / var(--tw-bg-opacity, 1));
  color: hsla(var(--bc) / var(--tw-text-opacity, 1))
}

html {
  -webkit-tap-highlight-color: transparent
}

:root {
  --p: 259 94% 51%;
  --pf: 259 94% 41%;
  --sf: 314 100% 38%;
  --af: 174 60% 41%;
  --nf: 219 14% 22%;
  --in: 198 93% 60%;
  --su: 158 64% 52%;
  --wa: 43 96% 56%;
  --er: 0 91% 71%;
  --inc: 198 100% 12%;
  --suc: 158 100% 10%;
  --wac: 43 100% 11%;
  --erc: 0 100% 14%;
  --rounded-box: 1rem;
  --rounded-btn: 0.5rem;
  --rounded-badge: 1.9rem;
  --animation-btn: 0.25s;
  --animation-input: .2s;
  --btn-text-case: uppercase;
  --btn-focus-scale: 0.95;
  --border-btn: 1px;
  --tab-border: 1px;
  --tab-radius: 0.5rem;
  --pc: 0 0% 100%;
  --s: 314 100% 47%;
  --sc: 0 0% 100%;
  --a: 174 60% 51%;
  --ac: 175 44% 15%;
  --n: 219 14% 28%;
  --nc: 0 0% 100%;
  --b1: 0 0% 100%;
  --b2: 0 0% 95%;
  --b3: 180 2% 90%;
  --bc: 215 28% 17%
}

*, ::before, ::after {
  --tw-border-spacing-x: 0;
  --tw-border-spacing-y: 0;
  --tw-ordinal:  ;
  --tw-slashed-zero:  ;
  --tw-numeric-figure:  ;
  --tw-numeric-spacing:  ;
  --tw-numeric-fraction:  
}

::backdrop {
  --tw-border-spacing-x: 0;
  --tw-border-spacing-y: 0;
  --tw-ordinal:  ;
  --tw-slashed-zero:  ;
  --tw-numeric-figure:  ;
  --tw-numeric-spacing:  ;
  --tw-numeric-fraction:  
}

@keyframes spin {
  from {
    transform: rotate(0deg)
  }

  to {
    transform: rotate(360deg)
  }
}

@keyframes button-pop {
  0% {
    transform: scale(var(--btn-focus-scale, 0.95))
  }

  40% {
    transform: scale(1.02)
  }

  100% {
    transform: scale(1)
  }
}

@keyframes checkmark {
  0% {
    background-position-y: 5px
  }

  50% {
    background-position-y: -2px
  }

  100% {
    background-position-y: 0
  }
}

@keyframes progress-loading {
  50% {
    left: 107%
  }
}

@keyframes radiomark {
  0% {
    box-shadow: 0 0 0 12px hsl(var(--b1)) inset, 0 0 0 12px hsl(var(--b1)) inset
  }

  50% {
    box-shadow: 0 0 0 3px hsl(var(--b1)) inset, 0 0 0 3px hsl(var(--b1)) inset
  }

  100% {
    box-shadow: 0 0 0 4px hsl(var(--b1)) inset, 0 0 0 4px hsl(var(--b1)) inset
  }
}

@keyframes rating-pop {
  0% {
    transform: translateY(-0.125em)
  }

  40% {
    transform: translateY(-0.125em)
  }

  100% {
    transform: translateY(0)
  }
}

@keyframes toast-pop {
  0% {
    transform: scale(0.9);
    opacity: 0
  }

  100% {
    transform: scale(1);
    opacity: 1
  }
}

.h-full {
  height: 100%
}

.w-full {
  width: 100%
}

.bg-blue-100 {
  --tw-bg-opacity: 1;
  background-color: rgb(219 234 254 / var(--tw-bg-opacity))
}

.text-primary {
  --tw-text-opacity: 1;
  color: hsl(var(--p) / var(--tw-text-opacity))
}
```

I can see both `.text-primary` and `--p` variable exist in the file, so I think my app can use primary color of daisyUI, but it does not.

![image](https://user-images.githubusercontent.com/41826375/192128901-7ec14a94-31e2-4e88-bb31-e256a4dcae2d.png)

It only has colors which comes from tailwind but not daisyUI. How can I apply daisyUI here? Thank you.
